Docs and examples for packages
webb-tools/webb.js pull request #197
Opened 2022-04-11 14:04 UTC by AhmedKorim

Closes #187

2022-04-11 17:35 UTC, nepoche requested changes
Nice documentation and examples! Just a few comments - let me know if there are any that you don't agree with.

2022-04-11 17:35 UTC, nepoche commented on packages/api-providers/src/abstracts/anchor/anchor-deposit.ts
> +// Todo: should we extract the interface of MixerDeposit on another class and rename `generateBridgeNote` to generate note?
```suggestion
// Todo: should we extract the interface of MixerDeposit on another class and rename `generateBridgeNote` to generate note
```
Agreed this refactor should take place - especially with the removal of tornado.

2022-04-11 17:35 UTC, nepoche commented on packages/api-providers/src/abstracts/mixer/mixer-withdraw.ts
> +  Done, // the withdraw is Done and seceded, the next tic the instance should be ideal
```suggestion
  Done, // the withdraw is Done and succeeded, the next tic the instance should be ideal
```

2022-04-11 17:35 UTC, nepoche commented on packages/api-providers/src/abstracts/relayer/webb-relayer.class.ts
> + * @param appConfig - App config is used for misc pursues
```suggestion
 * @param appConfig - App config is used for looking up configuration values for issuing queries on the relayers
```

2022-04-11 17:35 UTC, nepoche commented on packages/api-providers/src/abstracts/relayer/webb-relayer.class.ts
> + * @param leaves - Array of hex representation of the leave
```suggestion
 * @param leaves - Array of hex representation of the leaves
```

2022-04-11 17:35 UTC, nepoche commented on packages/api-providers/src/abstracts/relayer/webb-relayer.class.ts
> + * it will return the whole leaves, And what block number is used in the last pulling of leaves
```suggestion
 * Fetching leaves from the relayer is faster than querying a chain's node.
 * The relayer will return it's state for the given merkle tree - all of the leaves up to the latest synced block value.
```

2022-04-11 17:35 UTC, nepoche commented on packages/api-providers/src/abstracts/webb-provider.interface.ts
> + * @param relayingManager - Clean up for the provider that will remove the side effects
```suggestion
 * @param relayingManager - Object used by the provider for sending transactions or queries to a compatible relayer.
```

2022-04-11 17:35 UTC, nepoche commented on packages/api-providers/src/abstracts/webb-provider.interface.ts
> + * @param getProvider - A getter method for getting the underline provider
```suggestion
 * @param getProvider - A getter method for getting the underlying provider
```

2022-04-11 17:35 UTC, nepoche commented on packages/sdk-core/README.md
> +#  helpers for Zero-Knowledge and deposit notes it uses `wasm-utils`, and provider easier API
```suggestion
#  Helpers for Zero-Knowledge and Note generation
The package provides a cleaner API to the underlying `wasm-utils`
```

2022-04-11 17:35 UTC, nepoche commented on packages/sdk-core/README.md
> +For the browser it runs inside wasm
```suggestion
The note contains data about a deposit
```

2022-04-12 09:41 UTC, AhmedKorim commented on examples/node/sdk-core/mixer.ts
> +import {ProvingManagerSetupInput} from "@webb-tools/sdk-core/src";
I agree if it works the same way

2022-04-12 13:26 UTC, dutterbutter commented
I will follow up this PR with a subsequent pr that deploys typedocs to gh:pages.

2022-04-12 13:27 UTC, merged