Added vanchor poolshare script
webb-tools/webb.js pull request #262
Opened 2022-08-18 11:24 UTC by AhmedKorim

2022-08-19 06:12 UTC, drewstone requested changes
LGTM, some styling left before merge

2022-08-19 16:43 UTC, AtelyPham reviewed
I got an issue about the connection between `docker` and `polkadot` API.

<img width="800" alt="CleanShot 2022-08-19 at 23 42 29@2x" src="https://user-images.githubusercontent.com/60747384/185667114-16004db2-eb73-4cb9-81e3-c1483f61a29c.png">

2022-08-19 17:48 UTC, AhmedKorim commented
@AtelyPham  Seems this appeared after the percentage update

2022-08-19 17:49 UTC, drewstone commented
Yes you need to provide a nonce value now to these functions.

On Fri, Aug 19, 2022 at 1:48 PM Ahmed Korim ***@***.***>
wrote:

> @AtelyPham <https://github.com/AtelyPham> Seems this appeared after the
> percentage update
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/webb-tools/webb.js/pull/262#issuecomment-1220947953>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADELLF3X6XWVURXHZPNR5STVZ7CHFANCNFSM5642NRKQ>
> .
> You are receiving this because you commented.Message ID: <webb-tools/webb.
> ***@***.***>
>

2022-08-20 12:30 UTC, AtelyPham approved these changes
LGTM 👍 But the test failed. I wonder if it has any effect?

2022-08-21 10:06 UTC, drewstone commented
Yep, need to make sure the CI is fixed before merge.

2022-08-22 12:09 UTC, drewstone requested changes
Need to fix spelling @AhmedKorim

2022-08-22 12:09 UTC, drewstone commented on tests/integration_tests/substrate/wrapUnwrap.spec.ts
>      [apiPromise.tx.tokenWrapper.setWrappingFee( 1,id ,nonce)], singer);
Signer spelling `signer`

2022-08-22 12:23 UTC, drewstone approved these changes
LGTM

2022-08-22 12:29 UTC, merged