Introduce Vanchor Transaction for the Evm and Test Account Setup via the test-utils package
webb-tools/webb.js pull request #283
Opened 2022-09-08 19:37 UTC by dharjeezy

### PR Description

This PR introduces

1. Vanchor transaction method for EVM
2. Development account setup such as Alice, Bob, and Charlie for signing test transactions

2022-09-12 15:07 UTC, nepoche commented on packages/test-utils/src/config.ts
> +export interface EnabledContracts {
This file is relevant only to the relayer

2022-09-12 15:25 UTC, dharjeezy commented on packages/test-utils/src/localEvmChain.ts
> +export async function setupVanchorEvmTx (
Where can i find the one that exists in the `Anchors.VAnchor`?

2022-09-16 22:02 UTC, nepoche requested changes

2022-09-19 12:48 UTC, nepoche approved these changes

2022-09-20 13:00 UTC, merged